export interface Animal {
    type: string,
    image: string,
    breed: string[],
    colors: string[],
    weight: number,
    dob: string,
    gender: string,
    declawed: string,
    specialNeeds: string,
    specialNeedsReason: string,
    hairLength: string,
    goodWithCats: string,
    goodWithDogs: string,
    goodWithKids: string,
    bio: string,
    energyLevel: string,
    status: string,
    added: string,
    provider: string
}
